//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPoliMusicV4.ServiceReferenceSong {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceSong.WebServiceSongSoap")]
    public interface WebServiceSongSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadDataSet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReadDataSet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadDataSet", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> ReadDataSetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAppPoliMusicV4.ServiceReferenceSong.Song[] Read();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Read", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppPoliMusicV4.ServiceReferenceSong.Song[]> ReadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Create(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<int> CreateAsync(string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Update(int idSong, string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<int> UpdateAsync(int idSong, string name, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Delete(int idSong);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<int> DeleteAsync(int idSong);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Song : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string pathField;
        
        private int playsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
                this.RaisePropertyChanged("Path");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Plays {
            get {
                return this.playsField;
            }
            set {
                this.playsField = value;
                this.RaisePropertyChanged("Plays");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSongSoapChannel : WebAppPoliMusicV4.ServiceReferenceSong.WebServiceSongSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSongSoapClient : System.ServiceModel.ClientBase<WebAppPoliMusicV4.ServiceReferenceSong.WebServiceSongSoap>, WebAppPoliMusicV4.ServiceReferenceSong.WebServiceSongSoap {
        
        public WebServiceSongSoapClient() {
        }
        
        public WebServiceSongSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSongSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSongSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSongSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet ReadDataSet() {
            return base.Channel.ReadDataSet();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ReadDataSetAsync() {
            return base.Channel.ReadDataSetAsync();
        }
        
        public WebAppPoliMusicV4.ServiceReferenceSong.Song[] Read() {
            return base.Channel.Read();
        }
        
        public System.Threading.Tasks.Task<WebAppPoliMusicV4.ServiceReferenceSong.Song[]> ReadAsync() {
            return base.Channel.ReadAsync();
        }
        
        public int Create(string name, string path) {
            return base.Channel.Create(name, path);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(string name, string path) {
            return base.Channel.CreateAsync(name, path);
        }
        
        public int Update(int idSong, string name, string path) {
            return base.Channel.Update(idSong, name, path);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(int idSong, string name, string path) {
            return base.Channel.UpdateAsync(idSong, name, path);
        }
        
        public int Delete(int idSong) {
            return base.Channel.Delete(idSong);
        }
        
        public System.Threading.Tasks.Task<int> DeleteAsync(int idSong) {
            return base.Channel.DeleteAsync(idSong);
        }
    }
}
